version: '3.8'
services:
  database:
    container_name: stray-db
    image: "postgres:14.1-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "1339:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  app:
    container_name: stray-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=database
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_PORT=5432
      - DB_NAME=postgres
    depends_on:
      - database
    entrypoint: [ "/bin/bash", "./entrypoint.sh" ]
    restart: always

volumes:
  database-data:
